server:
  port: 8761

spring:
  application:
    name: eurekaserver

eureka:
  instance:
    hostname: master
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://master:8761/eureka/